### ISSUE TITLE
CBCT数据

### ISSUE THREAD

**Issue by Qianxunha** [qpuchen/nnUNet_att_position_correction#2]
感谢博主提供的代码，能分享下标注训练的CBCT数据嘛？
阿里天池大赛牙齿分割挑战赛MICCAI 2023 CBCT数据链接已经关闭了。
可以的话，十分感谢。这是我邮箱：[1634568659@qq.com]

**Comment by qpuchen** [comment]
抱歉，我也没保存CBCT数据。
